version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-4-my-coin-analyst"
    ports:
      - "8002:8080"
    volumes:
      - ./openapi:/openapi/
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml